import { z } from "zod"

const optionalInt = z.union([z.number().int().min(0), z.literal("")]).optional()

export const productSupplierSchema = z.object({
  supplier_id: z.number().int().positive(),
  vendor_code: z.string().max(64).optional(),
  is_preferred: z.boolean(),
})

export const inventoryFormSchema = z
  .object({
    sku: z.string().min(1, "SKU is required").max(64),
    name: z.string().min(1, "Name is required").max(255),
    description: z.string().optional(),
    barcode: z.string().max(64).optional(),
    qr_code: z.string().max(128).optional(),
    rfid_tag: z.string().max(128).optional(),
    alternate_codes: z.string().optional(),
    category_id: z.number().nullable(),
    sub_category: z.string().max(120).optional(),
    product_line: z.string().max(120).optional(),
    item_type: z.enum([
      "RAW",
      "FINISHED",
      "SEMI_FINISHED",
      "CONSUMABLE",
      "TRADING",
      "SERVICE",
      "ASSET",
    ]),
    size: z.string().max(64).optional(),
    color: z.string().max(64).optional(),
    model: z.string().max(120).optional(),
    variant: z.string().max(120).optional(),
    serial_number_flag: z.boolean(),
    batch_lot_flag: z.boolean(),
    roll_tracking_enabled: z.boolean(),
    batch_management_enabled: z.boolean(),
    expiry_date_flag: z.boolean(),
    shelf_life_days: optionalInt,
    primary_uom: z.string().min(1).max(32),
    secondary_uom: z.string().max(32).optional(),
    purchase_uom: z.string().max(32).optional(),
    sales_uom: z.string().max(32).optional(),
    conversion_factor: z.string().optional(),
    length: z.string().optional(),
    width: z.string().optional(),
    height: z.string().optional(),
    volume: z.string().optional(),
    gross_weight: z.string().optional(),
    net_weight: z.string().optional(),
    abc_class: z.enum(["A", "B", "C"]).optional().or(z.literal("")),
    xyz_class: z.enum(["FAST", "SLOW", "NON_MOVING"]).optional().or(z.literal("")),
    lifecycle_status: z.enum(["ACTIVE", "INACTIVE", "DISCONTINUED", "OBSOLETE"]),
    approval_status: z.enum(["DRAFT", "PENDING", "APPROVED", "REJECTED"]),
    tax_code: z.string().max(64).optional(),
    tax_rate_id: z.number().nullable(),
    hs_code: z.string().max(32).optional(),
    country_of_origin: z.string().max(64).optional(),
    hazardous_flag: z.boolean(),
    perishable_flag: z.boolean(),
    hazardous_material_class: z.string().max(64).optional(),
    regulatory_compliance_codes: z.string().optional(),
    price: z.number().min(0),
    cost_price: z.number().min(0),
    standard_cost: z.number().min(0).optional(),
    cost_valuation_method: z
      .enum(["STANDARD", "AVERAGE", "LAST_PURCHASE", "FIFO", "LIFO"])
      .optional()
      .or(z.literal("")),
    low_stock_threshold: z.number().min(0),
    reorder_level: z.number().min(0),
    max_stock_level: optionalInt,
    economic_order_qty: optionalInt,
    lead_time_days: optionalInt,
    default_supplier_id: z.number().int().positive().nullable(),
    default_warehouse_id: z.number().nullable(),
    default_location_id: z.number().nullable(),
    promotion_reorder_boost: z.boolean(),
    reorder_point: z.number().min(0),
    safety_stock_level: z.number().min(0),
    min_order_qty: optionalInt,
    max_order_qty: optionalInt,
    procurement_lead_time_days: optionalInt,
    demand_forecast_notes: z.string().optional(),
    quality_inspection_required: z.boolean(),
    inspection_checklist_json: z.string().optional(),
    expiry_alert_threshold_days: optionalInt,
    image_url: z.string().max(512).optional(),
    attachments_json: z.string().optional(),
    product_suppliers: z.array(productSupplierSchema),
    initial_stock: z.number().min(0).optional(),
    manufacturing_item_sku: z.string().max(64).optional(),
  })
  .superRefine((data, ctx) => {
    const hasSecondary = Boolean(data.secondary_uom?.trim())
    const hasConversion = Boolean(data.conversion_factor)
    if (hasSecondary && !hasConversion) {
      ctx.addIssue({
        code: "custom",
        message: "Conversion factor required when secondary UOM is set",
        path: ["conversion_factor"],
      })
    }
    if (hasConversion && !hasSecondary) {
      ctx.addIssue({
        code: "custom",
        message: "Secondary UOM required when conversion factor is set",
        path: ["secondary_uom"],
      })
    }
  })

export type InventoryFormValues = z.infer<typeof inventoryFormSchema>

export const defaultInventoryFormValues: InventoryFormValues = {
  sku: "",
  name: "",
  description: "",
  barcode: "",
  qr_code: "",
  rfid_tag: "",
  alternate_codes: "",
  category_id: null,
  sub_category: "",
  product_line: "",
  item_type: "TRADING",
  size: "",
  color: "",
  model: "",
  variant: "",
  serial_number_flag: false,
  batch_lot_flag: false,
  roll_tracking_enabled: false,
  batch_management_enabled: false,
  expiry_date_flag: false,
  shelf_life_days: "",
  primary_uom: "EA",
  secondary_uom: "",
  purchase_uom: "",
  sales_uom: "",
  conversion_factor: "",
  length: "",
  width: "",
  height: "",
  volume: "",
  gross_weight: "",
  net_weight: "",
  abc_class: "",
  xyz_class: "",
  lifecycle_status: "ACTIVE",
  approval_status: "DRAFT",
  tax_code: "",
  tax_rate_id: null,
  hs_code: "",
  country_of_origin: "",
  hazardous_flag: false,
  perishable_flag: false,
  hazardous_material_class: "",
  regulatory_compliance_codes: "",
  price: 0,
  cost_price: 0,
  standard_cost: 0,
  cost_valuation_method: "",
  low_stock_threshold: 0,
  reorder_level: 0,
  max_stock_level: "",
  economic_order_qty: "",
  lead_time_days: "",
  default_supplier_id: null,
  default_warehouse_id: null,
  default_location_id: null,
  promotion_reorder_boost: false,
  reorder_point: 0,
  safety_stock_level: 0,
  min_order_qty: "",
  max_order_qty: "",
  procurement_lead_time_days: "",
  demand_forecast_notes: "",
  quality_inspection_required: false,
  inspection_checklist_json: "",
  expiry_alert_threshold_days: "",
  image_url: "",
  attachments_json: "",
  product_suppliers: [],
  initial_stock: 0,
  manufacturing_item_sku: "",
}
